services:
  web:
    build: .
    environment:
      - ENVIRONMENT=production
    volumes:
      - .:/code
      - ./logs:/var/log/lexit
    ports:
      - 8000:80
    depends_on:
      - db
      - redis
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER:-fastapi} -d ${POSTGRES_DB:-${POSTGRES_USER:-postgres}}
      
      interval: 5s
      timeout: 5s
      retries: 120
      start_period: 30s
  db:
    image: postgres:17-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5438:5432
    environment:
      - POSTGRES_USER=fastapi
      - POSTGRES_PASSWORD=fastapi
      - POSTGRES_DB=fastapi

  redis:
    image: redis:8.0.1-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  postgres_data:
  redis_data: