services:
  web:
    build: .
    volumes:
      - .:/code
    ports:
      - 8000:80
    environment:
      - ENV=DEV
    depends_on:
      - db
    labels:
      - "monitoring=true"
  db:
    image: postgres:17-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5438:5432
    environment:
      - POSTGRES_USER=fastapi
      - POSTGRES_PASSWORD=fastapi
      - POSTGRES_DB=fastapi
  prometheus:
    image: prom/prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana

  postgres_exporter:
    image: prometheuscommunity/postgres-exporter
    environment:
      DATA_SOURCE_NAME: "postgresql://user:pass@db:5432/mydb?sslmode=disable"
    ports:
      - "9187:9187"
    depends_on:
      - db

volumes:
  postgres_data:
  grafana_data:
