services:
  db:
      image: postgres:17-alpine
      volumes:
        - postgres_data:/var/lib/postgresql/data/
      ports:
        - 5438:5432
      environment:
        - POSTGRES_USER=fastapi
        - POSTGRES_PASSWORD=fastapi
        - POSTGRES_DB=fastapi
  web:
    build: .
    environment:
      - ENVIRONMENT=production
    volumes:
      - .:/code
      - ./logs:/var/log/lexit
    ports:
      - 8000:80
    depends_on:
      - db
      - redis
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER:-fastapi} -d ${POSTGRES_DB:-${POSTGRES_USER:-postgres}}
      
      interval: 5s
      timeout: 5s
      retries: 120
      start_period: 30s


  redis:
    image: redis:8.0.1-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10


  worker_email:
    build: .
    command: python app/workers/email_worker.py
    volumes:
      - .:/code
    environment:
      - REDIS_HOST=redis
      - PYTHONPATH=/code
    depends_on:
      - redis

  rq-dashboard:
    image: eoranged/rq-dashboard
    ports:
      - "9181:9181"
    environment:
      - RQ_DASHBOARD_REDIS_URL=redis://redis:6379
    depends_on:
      - redis

volumes:
  postgres_data:
  redis_data: