sonar.python.coverage.reportPaths=coverage.xml

sonar.coverage.exclusions=app/tests/**, **/__init__.py, app/core/openapi.py, app/main.py, app/models/**, alembic/**, app/core/logger.py, app/core/email_client.py, app/workers/email_worker.py, app/config.py

sonar.exclusions= alembic/**, app/templates/**

sonar.issue.ignore.multicriteria=DF1

sonar.issue.ignore.multicriteria.DF1.resourceKey=**/Dockerfile

sonar.issue.ignore.multicriteria.DF1.ruleKey=docker:S6500