"""Add UserProvider

Revision ID: c2b140ee5c9e
Revises: 57f1472e3225
Create Date: 2025-06-29 15:43:59.721685

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c2b140ee5c9e"
down_revision: Union[str, None] = "57f1472e3225"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "userprovider",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "provider", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "provider_user_id",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=False,
        ),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_userprovider_provider"),
        "userprovider",
        ["provider"],
        unique=False,
    )
    op.create_index(
        op.f("ix_userprovider_provider_user_id"),
        "userprovider",
        ["provider_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_userprovider_user_id"),
        "userprovider",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_userprovider_user_id"), table_name="userprovider")
    op.drop_index(
        op.f("ix_userprovider_provider_user_id"), table_name="userprovider"
    )
    op.drop_index(op.f("ix_userprovider_provider"), table_name="userprovider")
    op.drop_table("userprovider")
    # ### end Alembic commands ###
