"""add refresh_token

Revision ID: cacbcb8942e3
Revises: 9c8ae5c9ed7a
Create Date: 2025-07-05 16:09:40.245179

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cacbcb8942e3"
down_revision: Union[str, None] = "9c8ae5c9ed7a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "userrefreshtoken",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "refresh_token", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "user_agent", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("revoked", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_userrefreshtoken_refresh_token"),
        "userrefreshtoken",
        ["refresh_token"],
        unique=False,
    )
    op.create_index(
        op.f("ix_userrefreshtoken_user_id"),
        "userrefreshtoken",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_userrefreshtoken_user_id"), table_name="userrefreshtoken"
    )
    op.drop_index(
        op.f("ix_userrefreshtoken_refresh_token"),
        table_name="userrefreshtoken",
    )
    op.drop_table("userrefreshtoken")
    # ### end Alembic commands ###
